#!/bin/zsh
# ファイルを連番で作成するコマンド

# エラー時の表示
if [[ $# -lt 3 ]]; then
  # $0 には実行したスクリプト名が入る
  echo "エラー: 引数が足りません。"
  echo "使い方: $0 <フォルダ共通名> <開始番号> <終了番号>"
  echo "実行例: $0 report_ 2024 2028"
  exit 1
fi

# 位置パラメータ
dirname=$1          # フォルダ名
first=$2            # 最初のフォルダの番号
last=$3             # 最後のフォルダの番号

# forループでフォルダを作成
for ((i=first; i<=last; i++)); do
  mkdir -p "${dirname}${i}"  # フォルダ名にスペースなどが含まれる可能性も考慮し、変数は""で囲むとより安全らしい
done

# 結果表示
echo "完了: ${dirname}${first} から ${dirname}${last} まで、計$((last-first+1))個のフォルダを作成しました。"