#!/bin/zsh

export CMD_DIR="$HOME/mycmd_scripts"       # サブコマンドが保存されているディレクトリのパス


# サブコマンドが指定されていない場合のエラー文
if [[ -z "$1" ]]; then
  echo "使い方: mycmd <サブコマンド> [引数...]"
  echo "利用可能なサブコマンド: mydir_for , cntf , pomodoro , nas , qrgen , forcus , ren_for , sharef"
  exit 1
fi

sub_command=$1      # 1番目の引数(サブコマンド名)
shift               # shiftコマンドで1番目の引数を削除 (残りの引数をサブコマンドに渡すため)

# サブコマンド
case $sub_command in
  "mkdir_for")                                          # ファイルを連番で作成するコマンド
    exec "$CMD_DIR/mkdir_for" "$@"
    ;;

  "cntf")                                               # フォルダ内のファイルの個数を数えるコマンド
    exec "$CMD_DIR/cntf" "$@"
    ;;

  "nas")                                                # 使用しているPCをNAS化するコマンド
    exec "$CMD_DIR/nas" "$@"
    ;;

  "pomodoro")                                           # 指定したセット数ポモドーロタイマーが作動する。(25分+5分ワンセット)(通知機能あり)
    exec "$CMD_DIR/pomodoro" "$@"
    ;;

  "qrgen")                                              # 指定したURLのQRコードを生成する
    exec "$CMD_DIR/qrgen" "$@"
    ;;

  "sharef")                                             # 指定したファイルを共有するためのURLを作成する。
    exec "$CMD_DIR/sharef" "$@"
    ;;

  "pyhttp")                                             # カレントディレクトリをWebサーバーにする
  
    exec "$CMD_DIR/pyhttp" "$@"
    ;;

  "ren_for")                                            # 指定した名前の連番ファイルの名前を変更する
    exec "$CMD_DIR/ren_for" "$@"
    ;;
    
  "forcus")                                             # 指定したファイルへのアクセスをブロックする
    exec "$CMD_DIR/forcus" "$@"
    ;;

  "crop")                                               # 指定したフォルダ内の画像を切り取る(クロップする)
    exec "$CMD_DIR/crop_center" "$@"
    ;;

  "chimg")                                               # 指定したフォルダ内の画像の拡張子を変更する(macのみ)
    exec "$CMD_DIR/chimg" "$@"
    ;;

  "trash")                                               # 指定したファイル、フォルダをゴミ箱に捨てる(macのみ)
    exec "$CMD_DIR/trash" "$@"
    ;;
    
  *)                                                    # エラー時の表示
    echo "エラー: '$sub_command' は不明なサブコマンドです。"  # エラー時の表示
    exit 1
    ;;
esac

